#!/bin/sh

build() {
	CARGO_TARGET_DIR=.melonbuild cargo build --release
}

if command -v "cargo" > /dev/null;
then
    if test -f ".melonbuild/release/melon";
    then
        ./.melonbuild/release/melon $@
    else
        build
        ./.melonbuild/release/melon $@
    fi
else
    echo "Melon requires rustc and cargo to be installed on your system."
    exit 1
fi